# Generated by Django 4.1.2 on 2022-10-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
