# Generated by Django 4.1.1 on 2022-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='bio',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
