# Generated by Django 4.1.2 on 2022-11-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usersetting_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isread',
            field=models.BooleanField(default=False),
        ),
    ]
