# Generated by Django 4.1.1 on 2022-09-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_usersetting_bio_usersetting_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
    ]
