# Generated by Django 4.1.2 on 2022-11-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='unread_by_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='unread_by_2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
