# Generated by Django 4.1.1 on 2022-09-28 21:19

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.random_file_name),
        ),
    ]
